services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    volumes:
      - ./weaviate-data:/var/lib/weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      CLUSTER_HOSTNAME: "node1"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: "http://t2v-transformers:8080"
      RAFT_BOOTSTRAP_EXPECTED: 1
      DISABLE_TELEMETRY: "false"
      RAFT_BOOTSTRAP_TIMEOUT: 300
    depends_on:
      t2v-transformers:
        condition: service_started
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://localhost:8080/v1/.well-known/ready || exit 1",
        ]
      interval: 15s
      timeout: 10s
      retries: 30
      start_period: 30s
    #restart: unless-stopped
    networks:
      - web

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    ports:
      - "8081:8080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://localhost:8080/v1/.well-known/ready || exit 1",
        ]
      interval: 15s
      timeout: 10s
      retries: 30
      start_period: 30s
    restart: unless-stopped
    networks:
      - web

  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    #restart: unless-stopped
    networks:
      - web

  ecomm-rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    #restart: unless-stopped
    networks:
      - web

  go-server:
    build:
      context: .
      dockerfile: products-service/Dockerfile

    ports:
      - "3000:3000"
      - "6060:6060"
    #restart: unless-stopped
    depends_on:
      weaviate:
        condition: service_healthy
      ecomm-rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - web

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
    networks:
      - web

  # openresty:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   container_name: openresty
  #   command: ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]
  #   volumes:
  #     - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
  #     - ./nginx/lua/jwt_auth.lua:/usr/local/openresty/nginx/lua/jwt_auth.lua
  #     - ./certbot/conf:/etc/letsencrypt:ro
  #     - ./certbot/www:/var/www/certbot
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   # environment:
  #   #   - JWT_SECRET=${JWT_SECRET}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - go-server
  #     # - grafana
  #     - weaviate
  #   networks:
  #     - web
  #   #profiles: ["dev"]
  #   restart: unless-stopped
  
  # certbot:
  #   image: certbot/certbot

  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: >
  #     sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot --email muneet.dhanker@omlogic.com --agree-tos --no-eff-email -d stagingai.solhapp.com"
  #   networks:
  #     - web

volumes:
  rabbitmq_data:
  redis-data:

networks:
  web:
    driver: bridge
