global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape Loki metrics
  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]

  # Scrape Promtail metrics
  - job_name: promtail
    static_configs:
      - targets: ["promtail:9080"]

  # Scrape OpenResty / NGINX metrics
  - job_name: openresty
    metrics_path: /metrics
    static_configs:
      - targets: ["openresty:80"]
